version: 2

jobs:
  build_dev:
    docker:
      - image: circleci/php:5.6-cli-node-browsers
    steps:
      - checkout
      - run:
          name: Hello World Step
          command: echo "Hello World"

workflows:
  version: 2
  build_flow:
    jobs:
      - build_dev:
          filters:
            branches:
              only: main