version: 2

jobs:
  build_dev:
    docker:
      - image: circleci/php:5.6-cli-node-browsers
    steps:
      - checkout
      - run:
          name: Hello World Step
          command: echo "Hello World"

      - run:
          name: Installing sshpass
          command: sudo apt-get install sshpass

      - run:
          name: Adding domain to know hosts
          command: ssh-keyscan -H 3.15.183.162 >> ~/.ssh/known_hosts

      - run:
          name: Moving to Beta
          command: sshpass -p a1b2c3d4e5 rsync -rlOtvz -e ssh /home/circleci/Garagebox-Prototype/ ubuntu@3.15.183.162:/var/www/html/Garagebox-Prototype/

workflows:
  version: 2
  build_flow:
    jobs:
      - build_dev:
          filters:
            branches:
              only: main